/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YgaBGYDZ2nG
 */
import { Button } from "@/components/ui/button"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Checkbox } from "@/components/ui/checkbox"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { SVGProps } from "react"
import AudioPlayer from "./audio-player"

export default function dashboard() {
  return (
    <div className="bg-white h-full">
      <header className="flex items-center justify-between p-6 border-b">
        <div className="flex items-center space-x-4">
          <div className="flex items-center gap-2">
            <img src="/logo.svg" className="w-8" />
            <h1 className="text-xl font-bold">tapetime</h1>
          </div>

          <div className="flex items-center space-x-1">
            <CheckIcon className="h-4 w-4 text-green-500" />
            <span className="text-sm font-medium">programadorcaro</span>
          </div>
          <div className="flex items-center space-x-1">
            <ClockIcon className="h-4 w-4 text-gray-500" />
            <span className="text-sm font-medium">tape-time</span>
          </div>
        </div>
        <div className="flex items-center space-x-4">
          <Button className="bg-red-500 text-white">Upload</Button>
          <Avatar>
            <AvatarImage alt="User avatar" src="/placeholder.svg?height=32&width=32" />
            <AvatarFallback>U</AvatarFallback>
          </Avatar>
        </div>
      </header>
      <div className="flex h-full">
        <nav className="w-56 p-6 space-y-2 border-r">
          <Link className="block" href="#">
            Docs
          </Link>
          <Link className="block font-bold" href="#">
            My Collections
          </Link>
          <Link className="block" href="#">
            Json Response
          </Link>
          <Link className="block" href="#">
            Plans & Billing
          </Link>
          <Link className="block" href="#">
            Settings
          </Link>
        </nav>
        <main className="flex-grow p-6">
          <h2 className="text-lg font-bold">Files</h2>
          <p className="text-sm text-gray-600 mb-4">
            These are all of the files that have been uploaded via your uploader.
          </p>
          <div className="grid grid-cols-2 gap-5 xl:grid-cols-3 2xl:grid-cols-4">
            <div>
              <h3 className="text-base mb-1 font-semibold">sim como descobriu</h3>
              <AudioPlayer />
            </div>
            <div>
              <h3 className="text-base mb-1 font-semibold">sim como descobriu</h3>
              <AudioPlayer />
            </div>
            <div>
              <h3 className="text-base mb-1 font-semibold">sim como descobriu</h3>
              <AudioPlayer />
            </div>
            <div>
              <h3 className="text-base mb-1 font-semibold">sim como descobriu</h3>
              <AudioPlayer />
            </div>
          </div>
        </main>
      </div>
    </div>
  )
}


function CheckIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  )
}


function ClockIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}
